export const galery = [
  [
    require("../assets/images/work/1/promotion1.png"),
    require("../assets/images/work/1/promotion2.png"),
    require("../assets/images/work/1/promotion3.png"),
    require("../assets/images/work/1/promotion4.png"),
  ],
  [
    require("../assets/images/work/2/promotion1.png"),
    require("../assets/images/work/2/promotion2.png"),
    require("../assets/images/work/2/promotion3.png"),
    require("../assets/images/work/2/promotion4.png"),
  ],
  [
    require("../assets/images/work/3/promotion1.png"),
    require("../assets/images/work/3/promotion2.png"),
    require("../assets/images/work/3/promotion3.png"),
    require("../assets/images/work/3/promotion4.png"),
  ],
  [
    require("../assets/images/work/4/promotion1.png"),
    require("../assets/images/work/4/promotion2.png"),
    require("../assets/images/work/4/promotion3.png"),
    require("../assets/images/work/4/promotion4.png"),
  ],
  [
    require("../assets/images/work/5/promotion1.png"),
    require("../assets/images/work/5/promotion2.png"),
    require("../assets/images/work/5/promotion3.png"),
    require("../assets/images/work/5/promotion4.png"),
  ],
  [
    require("../assets/images/work/6/promotion1.png"),
    require("../assets/images/work/6/promotion2.png"),
    require("../assets/images/work/6/promotion3.png"),
    require("../assets/images/work/6/promotion4.png"),
  ],
  [
    require("../assets/images/work/7/promotion1.png"),
    require("../assets/images/work/7/promotion2.png"),
    require("../assets/images/work/7/promotion3.png"),
    require("../assets/images/work/7/promotion4.png"),
  ],
];
